export const newOrderColumns = [
    { field: 'cod_art', headerName: 'Cód Art', width: 120, editable: true },
    { field: 'articulo', headerName: 'Artículo', width: 220, editable: false },
    {
      field: 'cantidad',
      headerName: 'Cantidad',
      type: 'number',
      width: 100,
      editable: false,
    },
    {
      field: 'place',
      headerName: 'Site',
      type: 'singleSelect',
      valueOptions: ['Pilar', 'Tortuguitas', 'Pets'],
      width: 100,
      editable: true,
    },
    {
      field: 'empresa',
      headerName: 'Empresa',
      type: 'singleSelect',
      valueOptions: ['Axon Buenos Aires','Axon Nutrición Animal','Ensol','EnsolFood','EnsolPigs','PSI'],
      width: 160,
      editable: true,
    },
    {
      field: 'fecha_entrega',
      headerName: 'F.Entrega',
      type: 'date',
      width: 100,
      editable: true,
    },
    {
      field: 'observaciones',
      headerName: 'Observaciones',
      width: 100,
      editable: false,
    },
    {
      field: 'leyenda1',
      headerName: 'Leyenda1',
      width: 100,
      editable: false,
    },
    {
      field: 'razon_social',
      headerName: 'Razon Social',
      width: 100,
      editable: false,
      hide: true,
    },
    {
      field: 'nombre_vendedor',
      headerName: 'Nombre vendedor',
      width: 100,
      editable: false,
      hide: true,
    },
    {
      field: 'fecha_pedido',
      headerName: 'F.Pedido',
      type: 'date',
      width: 100,
      editable: true,
      hide: true,
    },
    {
      field: 'fecha_apr',
      headerName: 'Fecha Apr',
      type: 'dateTime',
      width: 120,
      editable: true,
      hide: true,
    },
    {
      field: 'hora_apr',
      headerName: 'Hora Apr',
      type: 'Time',
      width: 100,
      editable: true,
      hide: true,
    },
    {
      field: 'estado',
      headerName: 'Estado',
      width: 100,
      editable: false,
      hide: true,
    },
    {
      field: 'leyenda4',
      headerName: 'Leyenda 4',
      width: 100,
      editable: false,
      hide: true,
    },
    {
      field: 'des_adicional',
      headerName: 'Desc. Adicional',
      width: 100,
      editable: false,
      hide: true,
    },
  ];

  export const pendingOrdersColumns = [
    { field: 'cod_art', headerName: 'Cód Art', width: 160, editable: false },
    { field: 'articulo', headerName: 'Artículo', width: 320, editable: false },
    {
      field: 'cantidad',
      headerName: 'Cantidad',
      type: 'number',
      width: 120,
      editable: false,
    },
    {
      field: 'place',
      headerName: 'Despacho',
      type: 'singleSelect',
      width: 160,
      editable: false,
    },
    { field: 'finished', headerName: 'Terminado', type: 'boolean', width: 120 },

  ];

